[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npm run build && npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/app.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
