[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate --schema=./prisma/schema.prisma && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy --schema=./prisma/schema.prisma && node dist/app.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3001
